version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
  npm-publisher: uraway/npm-publisher@0.2.0

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &save-cache
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules
  - &install-deps
    run:
      name: Install dependencies
      command: npm install
  - &build-packages
    run:
      name: Build
      command: npm run build
  - &run-unit-tests
    run:
      name: Test
      command: npm run test:ci
  - &update-npm-version
    run:
      name: Update NPM version
      command: 'sudo npm install -g npm@latest'
  - &copy-package-json
    run:
      name: Copy package.json to dist/lib
      command: cp -rf package.json dist/lib
  - &copy-readme
    run:
      name: Copy Readme.md to dist/lib
      command: cp -rf Readme.md dist/lib
  - &copy-changelog
    run:
      name: Copy CHANGELOG.md to dist/lib
      command: cp -rf CHANGELOG.md dist/lib
  - &copy-npmrc
    run:
      name: Copy .npmrc to dist/lib
      command: cp -rf .npmrc dist/lib
  - &go-to-dist-lib
    run:
      name: Go to dist/lib directory before publish
      command: cd dist/lib
  - &pre-release
    run:
      name: Create a pre release
      command: npm run pre-release
  - &npm-authenticate
    run:
      name: NPM Account Authentication
      command: //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
  - &npm-publish
    run:
      name: Publish package on npm
      command: npm run publish-alpha

commands:
  set-git-global-user:
    description: "Set your account's default identity"
    steps:
      - run: git config user.email ${USER_EMAIL}
      - run: git config user.name ${USER_NAME}
  copy-required-files-to-dist-lib:
    description: "Copy the publish required files to lib directory
    steps:
      - *copy-package-json
      - *copy-readme
      - *copy-changelog
      - *copy-npmrc

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *update-npm-version
      - *restore-cache
      - *install-deps
      - *save-cache
      - *build-packages
      - persist_to_workspace:
          root: .
          paths:
            - 'dist'

  unit_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *run-unit-tests
      - sonarcloud/scan

  pre-release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - attach_workspace:
          at: .
      - set-git-global-user
      - *pre-release
      - *npm-authenticate
      - copy-required-files-to-dist-lib
      - *go-to-dist-lib
      - *npm-publish

workflows:
  build-and-test-default:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - release
      - unit_tests:
          context: SONARCLOUD
          requires:
            - build
          filters:
            branches:
              ignore:
                - release

  build-test-and-publish-pre-release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release
      - unit_tests:
          context: SONARCLOUD
          requires:
            - build
          filters:
            branches:
              only:
                - release
      - pre-release:
          context: GIT
          requires:
            - build
            - unit_tests
          filters:
            branches:
              only:
                - release
