version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
  slack: circleci/slack@4.3.0
  jq: circleci/jq@2.2.0

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &save-cache
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules
  - &install-deps
    run:
      name: Install dependencies
      command: npm install
  - &build-packages
    run:
      name: Build
      command: npm run build
  - &run-unit-tests
    run:
      name: Test
      command: npm run test:ci
  - &update-npm-version
    run:
      name: Update NPM version
      command: 'sudo npm install -g npm@latest'
  - &checkout-release-branch
    run:
      name: Create a release branch
      command: git checkout -b release
  - &pre-release
    run:
      name: Create a pre release
      command: npm run pre-release
  - &npm-git-tags
    run:
      name: git push follow release tag
      command: git push --follow-tags -q https://${GH_TOKEN}@github.com/MikeDev75015/mongodb-pipeline-builder.git release

commands:
  merge-release-branch:
    description: "Merge the release branch in main"
    steps:
      - run:
          name: Checkout to release
          command: git checkout release
      - run:
          name: Checkout to main
          command: git checkout main
      - run:
          name: Merge release branch
          command: git merge release
      - run:
          name: Delete release branch
          command: git branch -d release

  authenticate-and-publish:
    description: "Authenticate to npm account and publish latest package version"
    steps:
      - run:
          name: NPM Account Authentication
          command: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      - run:
          name: Publish package on npm
          command: npm run publish-latest

  set-git-local-user:
    description: "Set the account's default identity"
    steps:
      - run: git config credential.helper 'cache --timeout=120'
      - run: git config user.email ${USER_EMAIL}
      - run: git config user.name ${USER_NAME}

  copy-required-files-to-dist:
    description: "Copy the publish required files to lib directory"
    steps:
      - run:
          name: Copy Readme.md to dist
          command: cp -rf Readme.md dist
      - run:
          name: Copy CHANGELOG.md to dist
          command: cp -rf CHANGELOG.md dist
      - run:
          name: Copy LICENSE to dist
          command: cp -rf LICENSE dist
      - run:
          name: Copy package.json to dist
          command: cp -rf package.json dist

  install-github-cli:
    description: Installs latest Github CLI
    steps:
      - jq/install
      - run:
          name: Install Github CLI
          description: Gets latest realease version of Github CLI
          command: |
            LATEST_RELEASE=$(curl -s https://api.github.com/repos/cli/cli/releases/latest)
            VERSION=$(echo $LATEST_RELEASE | jq -r '.tag_name')
            DEB_URL=$(echo $LATEST_RELEASE | jq -r '.assets[].browser_download_url | select(. | contains("linux_amd64.deb"))')
            wget --quiet -O gh_latest.deb $DEB_URL
            sudo apt install ./gh_latest.deb

  authenticate-github:
    description: Authentication to github
    steps:
      - run: echo $GH_TOKEN > ghtoken.txt
      - run: gh auth login --with-token < ghtoken.txt
      - run: gh pr create -H release -f -B main

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *update-npm-version
      - *restore-cache
      - *install-deps
      - *save-cache
      - *build-packages
      - persist_to_workspace:
          root: .
          paths:
            - 'dist'
      - slack/notify:
          event: fail
          template: basic_fail_1

  unit_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *run-unit-tests
      - sonarcloud/scan
      - slack/notify:
          event: fail
          template: basic_fail_1

  prepare-pre-release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - attach_workspace:
          at: .
      - set-git-local-user
      - *checkout-release-branch
      - *pre-release
      - *npm-git-tags
      - slack/notify:
          event: fail
          template: basic_fail_1

  publish-package:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - attach_workspace:
          at: .
      - copy-required-files-to-dist
      - authenticate-and-publish
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify-success-job:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - slack/notify:
          event: always
          template: basic_success_1

  merge-release-main:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - set-git-local-user
      - merge-release-branch
      - slack/notify:
          event: fail
          template: basic_fail_1

  create-pull-request:
    docker:
      - image: circleci/node:12
    steps:
      - install-github-cli
      - authenticate-github

workflows:
  build-and-test-main:
    when:
      not: << pipeline.git.tag >>
    jobs:
      - approval-build-and-test-main:
          type: approval
          filters:
            branches:
              ignore:
                - release
                - test
      - build:
          requires:
            - approval-build-and-test-main
          context: SLACK
          filters:
            branches:
              ignore:
                - release
                - test
      - unit_tests:
          context:
            - SONARCLOUD
            - SLACK
          requires:
            - build
          filters:
            branches:
              ignore:
                - release
                - test
      - notify-success-job:
          name: build-unit_tests-success
          context: SLACK
          requires:
            - build
            - unit_tests
          filters:
            branches:
              ignore:
                - release
                - test
      - approval-prepare-pre-release:
          type: approval
          requires:
            - build
            - unit_tests
            - build-unit_tests-success
          filters:
            branches:
              ignore:
                - release
                - test
              only:
                - main
      - prepare-pre-release:
          context:
            - GIT
            - SLACK
          requires:
            - build
            - unit_tests
            - build-unit_tests-success
            - approval-prepare-pre-release
          filters:
            branches:
              ignore:
                - release
                - test
              only:
                - main
      - notify-success-job:
          name: prepare-pre-release-success
          context: SLACK
          requires:
            - build
            - unit_tests
            - build-unit_tests-success
            - approval-prepare-pre-release
            - prepare-pre-release
          filters:
            branches:
              ignore:
                - release
                - test
              only:
                - main

  publish-release:
    jobs:
      - build:
          context: SLACK
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-package:
          context:
            - GIT
            - SLACK
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - merge-release-main:
          context:
            - GIT
            - SLACK
          requires:
            - build
            - publish-package
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - notify-success-job:
          name: publish-and-merge-release-success
          context: SLACK
          requires:
            - build
            - publish-package
            - merge-release-main
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

  test-github-cli:
    when:
      not: << pipeline.git.tag >>
    jobs:
      - merge-release-main:
          context:
            - GIT
            - SLACK
          filters:
            branches:
              only:
                - test
      - create-pull-request:
          requires:
            - merge-release-main
          context:
            - GIT
            - SLACK
          filters:
            branches:
              only:
                - test
