version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
  npm-publisher: uraway/npm-publisher@0.2.0

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &save-cache
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules
  - &install-deps
    run:
      name: Install dependencies
      command: npm install
  - &build-packages
    run:
      name: Build
      command: npm run build
  - &run-unit-tests
    run:
      name: Test
      command: npm run test:ci
  - &update-npm-version
    run:
      name: Update NPM version
      command: 'sudo npm install -g npm@latest'
  - &copy-package-json
    run:
      name: Copy package.json to dist/lib
      command: npm run copypackage
  - &pre-release
    run:
      name: Create a pre release
      command: npm run pre-release
  - &npm-publish
    run:
      name: Publish package on npm
      command: npm run publish-alpha


jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *update-npm-version
      - *restore-cache
      - *install-deps
      - *save-cache
      - *build-packages
      - persist_to_workspace:
          root: .
          paths:
            - 'dist'

  unit_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      #- *install-deps
      - *run-unit-tests
      - sonarcloud/scan

  pre-release:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: .
      - *copy-package-json
      - *pre-release
      - *npm-publish

workflows:
  build-and-test-ignore-release:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - release
      - unit_tests:
          context: SONARCLOUD
          requires:
            - build
          filters:
            branches:
              ignore:
                - release

  build-test-and-pre-release-only-release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release
      - unit_tests:
          context: SONARCLOUD
          requires:
            - build
          filters:
            branches:
              only:
                - release
      - pre-release:
          filters:
            branches:
              only:
                - release
